name: hello

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   issues:
#     types: [opened, edited, milestoned]
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 
     
      - name: print
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: execute py script 
        run: python example.py "Saying Hello from workflow"

<<<<<<< HEAD
      - name: echo hello
        run: echo "Hello World"

  Something:
    runs-on: ubuntu-latest
    name: Something
    steps:
      - name: Hello MacOs
        run: echo "hello from MACOS"
=======
  get-bq-data:
    runs-on: macos-11
    name: Get GA4 data from BQ
    steps:
      - name: Set env
        run: echo "hello from MACOS"

>>>>>>> cb4b35dfb1cb86f4baa307f00427388b953fb2a9
